const destinos = [
  {
    id: 1,
    name: "Cancún",
    description: "BUE → CUN",
    prize: 100,
    img: "./assets/img-destinos/cancun.jpg",
    category: "internacionales",
  },
  {
    id: 2,
    name: "Barcelona",
    description: "BUE ⇄ BCN",
    prize: 200,
    img: "./assets/img-destinos/barcelona.jpg",
    category: "internacionales",
  },
  {
    id: 3,
    name: "Madrid",
    description: "BUE ⇄ MAD",
    prize: 100,
    img: "./assets/img-destinos/madrid.jpg",
    category: "internacionales",
  },
  {
    id: 4,
    name: "Montevideo",
    description: "BUE → MVD",
    prize: 400,
    img: "./assets/img-destinos/montevideo.jpg",
    category: "internacionales",
  },
  {
    id: 5,
    name: "Rio de Janeiro",
    description: "BUE ⇄ GIG",
    prize: 430,
    img: "./assets/img-destinos/rio.jpg",
    category: "internacionales",
  },
  {
    id: 6,
    name: "Miami",
    description: "BUE → MIA",
    prize: 800,
    img: "./assets/img-destinos/miami.jpg",
    category: "internacionales",
  },
  {
    id: 7,
    name: "Qatar",
    description: "BUE → QR",
    prize: 1100,
    img: "./assets/img-destinos/qatar.jpg",
    category: "internacionales",
  },
  {
    id: 8,
    name: "Mendoza",
    description: "BUE ⇄ MDZ",
    prize: 900,
    img: "./assets/img-destinos/mendoza.jpg",
    category: "nacionales",
  },
  {
    id: 9,
    name: "Salta",
    description: "BUE → SLA",
    prize: 700,
    img: "./assets/img-destinos/salta.jpg",
    category: "nacionales",
  },
  {
    id: 10,
    name: "El Calafate",
    description: "BUE ⇄ FTE",
    prize: 900,
    img: "./assets/img-destinos/calafate.jpg",
    category: "nacionales",
  },
  {
    id: 11,
    name: "Ushuaia",
    description: "BUE → USH",
    prize: 600,
    img: "./assets/img-destinos/ushuaia.jpg",
    category: "nacionales",
  },
  {
    id: 12,
    name: "Bariloche",
    description: "BUE ⇄ BRC",
    prize: 800,
    img: "./assets/img-destinos/bariloche.jpg",
    category: "nacionales",
  },
  {
    id: 13,
    name: "Iguazú",
    description: "BUE → IGR",
    prize: 200,
    img: "./assets/img-destinos/iguazu.jpg",
    category: "nacionales",
  },
];
